// AUTO-GENERATED by mahraj-plants-importer — do not edit by hand.
// Re-run the importer to update. Safe for Postgres seeding via products.json.
export interface Category {
  id: string;
  slug: string;
  name: string;
}

export interface Product {
  id: string;
  slug: string;
  title: string;
  description: string;
  image: string;
  category_id: string;
}
